use customer_behavior;
 select * from customers;

-- Q1. What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as total_revenue 
from customers group by gender;

-- Q2. which customers used a discount but still spent more than the average purchase amount ?
select customer_id , purchase_amount from customers
where discount_applied ='Yes' and purchase_amount >=(select AVG(purchase_amount) from customers );

-- Q3. Which are the top 5 products with the highest average review rating ?
select item_purchased, avg(review_rating) as 'Average Rating'
from customers
group by item_purchased  order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amount between standard and express shipping ?
select shipping_type, round(avg(purchase_amount) ,2)
from customers
where shipping_type in ('Express', 'Standard')
group by shipping_type;

-- Q5.Do subcribed customer spend more ? compare average spend and total revenue between subcribers and non-subcribers
select subscription_status, count(customer_id) as 'total customers', avg(purchase_amount) as 'Average Spend' , sum(purchase_amount) as 'total revenue'
from customers
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discount applied ?
select item_purchased,
round(sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*) *100 ,2) as discount_Rate
from customers
group by item_purchased 
order by  discount_Rate desc
limit 5;

-- Q7. Segment customers into new, Returning and loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id , previous_purchases,
case 
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal' 
     end as customer_segment
     from customers 
     )
     select customer_segment, count(*) as 'Number of customers'
     from customer_type
     group by customer_segment;
     
-- Q8.What are the top 3 most purchased product within each category
with top_product as (
select category, item_purchased , count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers 
group by category , item_purchased
)
select item_rank,  category, item_purchased,total_orders
from top_product
where item_rank <=3;

-- Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subcribe?
select subscription_status,count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

-- Q10. What is revenue contribution of each age group ?
select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;

     
     